CREATE TABLE CORE_RUNTIME_REQUIREMENT
(
  RUNTIME_ID                VARCHAR2(36)  NOT NULL
, REVISION                  INTEGER       NOT NULL
, OWNER_TYPE                VARCHAR2(20)  NOT NULL
, OWNER_KEY                 VARCHAR2(100) NOT NULL
, REQUIRING_APPLICATION_NAME VARCHAR2(30)
, PACKAGE_NAME              VARCHAR2(100) NOT NULL
, PACKAGE_VERSION           VARCHAR2(100) NOT NULL
, REQUIREMENT_TYPE          VARCHAR2(20)  NOT NULL
, CONSTRAINT CORE_RUNTIME_REQUIREMENT_PK  PRIMARY KEY (RUNTIME_ID, REVISION, OWNER_TYPE, OWNER_KEY, PACKAGE_NAME)
, CONSTRAINT CORE_RUNTIME_REQUIREMENT_FK1 FOREIGN KEY (RUNTIME_ID, REVISION, PACKAGE_NAME)
      REFERENCES CORE_RUNTIME_CONTRIBUTION (RUNTIME_ID, REVISION, PACKAGE_NAME)
, CONSTRAINT CORE_RUNTIME_REQUIREMENT_FK2 FOREIGN KEY (REQUIRING_APPLICATION_NAME) REFERENCES APPLICATION (APPLICATION_NAME)
, CONSTRAINT CORE_RUNTIME_REQUIREMENT_CK1 CHECK (OWNER_TYPE IN ('APPLICATION','MANUAL_RUNTIME_ROOT') )
, CONSTRAINT CORE_RUNTIME_REQUIREMENT_CK2 CHECK (REQUIREMENT_TYPE IN ('ROOT','DIRECT','TRANSITIVE') )
, CONSTRAINT CORE_RUNTIME_REQUIREMENT_CK3 CHECK (
      (OWNER_TYPE = 'APPLICATION' AND REQUIRING_APPLICATION_NAME IS NOT NULL)
      OR (OWNER_TYPE = 'MANUAL_RUNTIME_ROOT' AND REQUIRING_APPLICATION_NAME IS NULL)
  )
)
;

COMMENT ON TABLE  CORE_RUNTIME_REQUIREMENT                          IS 'Why an installed application or manual runtime-only root needs a contribution. A contribution remains desired while at least one requirement references it.';
--
COMMENT ON COLUMN CORE_RUNTIME_REQUIREMENT.RUNTIME_ID                IS 'PK 1/5.';
COMMENT ON COLUMN CORE_RUNTIME_REQUIREMENT.REVISION                  IS 'PK 2/5.';
COMMENT ON COLUMN CORE_RUNTIME_REQUIREMENT.OWNER_TYPE                IS 'PK 3/5. APPLICATION or MANUAL_RUNTIME_ROOT.';
COMMENT ON COLUMN CORE_RUNTIME_REQUIREMENT.OWNER_KEY                 IS 'PK 4/5. Application name, or the normalized (version-independent) package_name of a manual runtime root.';
COMMENT ON COLUMN CORE_RUNTIME_REQUIREMENT.REQUIRING_APPLICATION_NAME IS 'FK to APPLICATION. Required and equal to OWNER_KEY only when OWNER_TYPE=APPLICATION.';
COMMENT ON COLUMN CORE_RUNTIME_REQUIREMENT.PACKAGE_NAME               IS 'PK 5/5. FK (with RUNTIME_ID, REVISION) to CORE_RUNTIME_CONTRIBUTION; the required contribution.';
COMMENT ON COLUMN CORE_RUNTIME_REQUIREMENT.PACKAGE_VERSION            IS 'The version this owner required. Must match the referenced contribution''s version or staging rejects the revision as a conflict.';
COMMENT ON COLUMN CORE_RUNTIME_REQUIREMENT.REQUIREMENT_TYPE           IS 'ROOT, DIRECT, or TRANSITIVE.';
