CREATE TABLE CORE_RUNTIME_REVISION
(
  RUNTIME_ID      VARCHAR2(36)  NOT NULL
, REVISION        INTEGER       NOT NULL
, OPERATION_ID    VARCHAR2(36)  NOT NULL
, ATTEMPT_NUMBER  INTEGER       NOT NULL
, PLAN_DIGEST     VARCHAR2(128) NOT NULL
, REVISION_STATUS VARCHAR2(20)  DEFAULT 'STAGED' NOT NULL
, CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
, COMPLETED_AT    TIMESTAMP WITH TIME ZONE
, CONSTRAINT CORE_RUNTIME_REVISION_PK  PRIMARY KEY (RUNTIME_ID, REVISION)
, CONSTRAINT CORE_RUNTIME_REVISION_FK1 FOREIGN KEY (RUNTIME_ID) REFERENCES CORE_SCHEMA_RUNTIME (RUNTIME_ID)
, CONSTRAINT CORE_RUNTIME_REVISION_CK1 CHECK (REVISION >= 1)
, CONSTRAINT CORE_RUNTIME_REVISION_CK2 CHECK (REVISION_STATUS IN ('STAGED','DATABASE_COMPLETE','ACTIVE','SUPERSEDED','REMOVED','FAILED') )
)
;

COMMENT ON TABLE  CORE_RUNTIME_REVISION                 IS 'Immutable header for each complete desired schema-runtime revision. Never a partial patch to a prior revision.';
--
COMMENT ON COLUMN CORE_RUNTIME_REVISION.RUNTIME_ID       IS 'PK 1/2. FK to CORE_SCHEMA_RUNTIME.';
COMMENT ON COLUMN CORE_RUNTIME_REVISION.REVISION         IS 'PK 2/2. Assigned by stage_runtime_revision_p; monotonically increasing per runtime_id.';
COMMENT ON COLUMN CORE_RUNTIME_REVISION.OPERATION_ID     IS 'The fenced operation that proposed this revision.';
COMMENT ON COLUMN CORE_RUNTIME_REVISION.ATTEMPT_NUMBER   IS 'The operation attempt that proposed this revision.';
COMMENT ON COLUMN CORE_RUNTIME_REVISION.PLAN_DIGEST      IS 'Digest of the normalized contribution/requirement set, computed and stored at staging time. Compared against the activation receipt, never a receipt checksum itself.';
COMMENT ON COLUMN CORE_RUNTIME_REVISION.REVISION_STATUS  IS 'STAGED, DATABASE_COMPLETE, ACTIVE, SUPERSEDED, REMOVED, or FAILED.';
COMMENT ON COLUMN CORE_RUNTIME_REVISION.COMPLETED_AT     IS 'Set when the revision leaves STAGED/DATABASE_COMPLETE for a terminal or ACTIVE status.';
