CREATE SEQUENCE CORE_CAPABILITY_AUDIT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE CORE_CAPABILITY_AUDIT
(
  AUDIT_ID       INTEGER      NOT NULL
, CAPABILITY_KEY VARCHAR2(100) NOT NULL
, OLD_VALUE      VARCHAR2(100)
, NEW_VALUE      VARCHAR2(100)
, ACTOR          VARCHAR2(128)
, CHANGED_AT     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
, CONSTRAINT CORE_CAPABILITY_AUDIT_PK PRIMARY KEY (AUDIT_ID)
)
;

COMMENT ON TABLE  CORE_CAPABILITY_AUDIT                IS 'Append-only audit trail for lifecycle capability and profile changes made through PKG_APP_DICT. Never updated or deleted.';
--
COMMENT ON COLUMN CORE_CAPABILITY_AUDIT.AUDIT_ID        IS 'PK. Surrogate, from CORE_CAPABILITY_AUDIT_SEQ.';
COMMENT ON COLUMN CORE_CAPABILITY_AUDIT.CAPABILITY_KEY  IS 'The APP_DICTIONARY key changed, e.g. DBPM_ALLOW_RUNTIME_REPLACE or DBPM_LIFECYCLE.';
COMMENT ON COLUMN CORE_CAPABILITY_AUDIT.OLD_VALUE       IS 'Value before the change; NULL if the key was previously unset.';
COMMENT ON COLUMN CORE_CAPABILITY_AUDIT.NEW_VALUE       IS 'Value after the change.';
COMMENT ON COLUMN CORE_CAPABILITY_AUDIT.ACTOR           IS 'Caller-supplied actor identity for this change.';
COMMENT ON COLUMN CORE_CAPABILITY_AUDIT.CHANGED_AT      IS 'Timestamp of the change.';
