CREATE TABLE CORE_OPERATION_STEP
(
  OPERATION_ID   VARCHAR2(36)   NOT NULL
, ATTEMPT_NUMBER INTEGER        NOT NULL
, STEP_NAME      VARCHAR2(60)   NOT NULL
, STEP_STATUS    VARCHAR2(30)   NOT NULL
, DETAIL         VARCHAR2(4000)
, RECORDED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
, CONSTRAINT CORE_OPERATION_STEP_PK  PRIMARY KEY (OPERATION_ID, ATTEMPT_NUMBER, STEP_NAME)
, CONSTRAINT CORE_OPERATION_STEP_FK1 FOREIGN KEY (OPERATION_ID) REFERENCES CORE_OPERATION (OPERATION_ID)
)
;

COMMENT ON TABLE  CORE_OPERATION_STEP                  IS 'Append/upsert evidence of lifecycle steps recorded against a fenced operation attempt.';
--
COMMENT ON COLUMN CORE_OPERATION_STEP.OPERATION_ID     IS 'PK 1/3. FK to CORE_OPERATION.';
COMMENT ON COLUMN CORE_OPERATION_STEP.ATTEMPT_NUMBER   IS 'PK 2/3. The attempt that recorded this evidence.';
COMMENT ON COLUMN CORE_OPERATION_STEP.STEP_NAME        IS 'PK 3/3. Caller-defined step identity, e.g. RUNTIME_STAGED.';
COMMENT ON COLUMN CORE_OPERATION_STEP.STEP_STATUS      IS 'Caller-defined step status, e.g. RESOLVED, DATABASE_COMPLETE, FAILED.';
COMMENT ON COLUMN CORE_OPERATION_STEP.DETAIL           IS 'Optional free-form evidence reference (never executable content).';
