CREATE SEQUENCE CORE_RUNTIME_ACK_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE CORE_RUNTIME_ACK
(
  ACK_ID               INTEGER       NOT NULL
, RUNTIME_ID           VARCHAR2(36)  NOT NULL
, REVISION             INTEGER       NOT NULL
, OPERATION_ID         VARCHAR2(36)  NOT NULL
, ATTEMPT_NUMBER       INTEGER       NOT NULL
, FENCING_TOKEN        VARCHAR2(32)  NOT NULL
, GENERATION           VARCHAR2(100)
, RECEIPT_CHECKSUM     VARCHAR2(128)
, ACKNOWLEDGEMENT_TYPE VARCHAR2(20)  NOT NULL
, ACKNOWLEDGED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
, CONSTRAINT CORE_RUNTIME_ACK_PK  PRIMARY KEY (ACK_ID)
, CONSTRAINT CORE_RUNTIME_ACK_FK1 FOREIGN KEY (RUNTIME_ID, REVISION) REFERENCES CORE_RUNTIME_REVISION (RUNTIME_ID, REVISION)
, CONSTRAINT CORE_RUNTIME_ACK_CK1 CHECK (ACKNOWLEDGEMENT_TYPE IN ('ACTIVE','VALIDATED','UNREACHABLE','REMOVED') )
)
;

COMMENT ON TABLE  CORE_RUNTIME_ACK                        IS 'Append-only durable evidence received from dbpm after filesystem work. Never updated or deleted.';
--
COMMENT ON COLUMN CORE_RUNTIME_ACK.ACK_ID                 IS 'PK. Surrogate, from CORE_RUNTIME_ACK_SEQ.';
COMMENT ON COLUMN CORE_RUNTIME_ACK.RUNTIME_ID              IS 'FK (with REVISION) to CORE_RUNTIME_REVISION.';
COMMENT ON COLUMN CORE_RUNTIME_ACK.OPERATION_ID            IS 'The fenced operation that recorded this acknowledgement.';
COMMENT ON COLUMN CORE_RUNTIME_ACK.ATTEMPT_NUMBER          IS 'The operation attempt that recorded this acknowledgement.';
COMMENT ON COLUMN CORE_RUNTIME_ACK.FENCING_TOKEN           IS 'The fencing token presented for this acknowledgement, retained as evidence. Not a secret.';
COMMENT ON COLUMN CORE_RUNTIME_ACK.GENERATION              IS 'Activated filesystem generation reported by dbpm.';
COMMENT ON COLUMN CORE_RUNTIME_ACK.RECEIPT_CHECKSUM        IS 'Verified aggregate receipt checksum, recorded here for the first time (never a staging input).';
COMMENT ON COLUMN CORE_RUNTIME_ACK.ACKNOWLEDGEMENT_TYPE    IS 'ACTIVE, VALIDATED, UNREACHABLE, or REMOVED.';
