CREATE TABLE CORE_OPERATION_SCOPE
(
  SCOPE_KEY    VARCHAR2(60)  NOT NULL
, OPERATION_ID VARCHAR2(36)  NOT NULL
, IS_PRIMARY   VARCHAR2(1)   DEFAULT 'N' NOT NULL
, CONSTRAINT CORE_OPERATION_SCOPE_PK  PRIMARY KEY (SCOPE_KEY)
, CONSTRAINT CORE_OPERATION_SCOPE_FK1 FOREIGN KEY (OPERATION_ID) REFERENCES CORE_OPERATION (OPERATION_ID)
, CONSTRAINT CORE_OPERATION_SCOPE_CK1 CHECK (IS_PRIMARY IN ('Y','N') )
)
;

CREATE INDEX CORE_OPERATION_SCOPE_IX1 ON CORE_OPERATION_SCOPE (OPERATION_ID);

COMMENT ON TABLE  CORE_OPERATION_SCOPE             IS 'The current claim holder for each scope key. A row existing means the scope is currently claimed by OPERATION_ID; scope keys are freed by deleting the row.';
--
COMMENT ON COLUMN CORE_OPERATION_SCOPE.SCOPE_KEY    IS 'PK. One of SCHEMA_LIFECYCLE, SCHEMA_RUNTIME, or APPLICATION:<name>.';
COMMENT ON COLUMN CORE_OPERATION_SCOPE.OPERATION_ID IS 'FK to CORE_OPERATION. The current holder of this scope.';
COMMENT ON COLUMN CORE_OPERATION_SCOPE.IS_PRIMARY   IS 'Y when this scope key is the owning operation''s primary scope, N for a participant scope.';
