CREATE TABLE CORE_RUNTIME_CONTRIBUTION
(
  RUNTIME_ID         VARCHAR2(36)  NOT NULL
, REVISION           INTEGER       NOT NULL
, PACKAGE_NAME       VARCHAR2(100) NOT NULL
, PACKAGE_VERSION    VARCHAR2(100) NOT NULL
, APPLICATION_NAME   VARCHAR2(30)
, ARTIFACT_URI       VARCHAR2(1000)
, ARTIFACT_CHECKSUM  VARCHAR2(128)
, CHECKSUM_ALGORITHM VARCHAR2(20)
, PAYLOAD_DIGEST     VARCHAR2(128)
, MANIFEST_DIGEST    VARCHAR2(128)
, CONSTRAINT CORE_RUNTIME_CONTRIBUTION_PK  PRIMARY KEY (RUNTIME_ID, REVISION, PACKAGE_NAME)
, CONSTRAINT CORE_RUNTIME_CONTRIBUTION_FK1 FOREIGN KEY (RUNTIME_ID, REVISION) REFERENCES CORE_RUNTIME_REVISION (RUNTIME_ID, REVISION)
, CONSTRAINT CORE_RUNTIME_CONTRIBUTION_FK2 FOREIGN KEY (APPLICATION_NAME) REFERENCES APPLICATION (APPLICATION_NAME)
)
;

COMMENT ON TABLE  CORE_RUNTIME_CONTRIBUTION                    IS 'The package identities contained in a complete runtime revision. At most one row per package_name per revision (CORE_RUNTIME_CONTRIBUTION_PK); a version conflict is rejected before staging, never represented as two sibling rows.';
--
COMMENT ON COLUMN CORE_RUNTIME_CONTRIBUTION.RUNTIME_ID          IS 'PK 1/3. FK to CORE_RUNTIME_REVISION.';
COMMENT ON COLUMN CORE_RUNTIME_CONTRIBUTION.REVISION            IS 'PK 2/3.';
COMMENT ON COLUMN CORE_RUNTIME_CONTRIBUTION.PACKAGE_NAME        IS 'PK 3/3.';
COMMENT ON COLUMN CORE_RUNTIME_CONTRIBUTION.PACKAGE_VERSION     IS 'The single version of PACKAGE_NAME desired in this revision.';
COMMENT ON COLUMN CORE_RUNTIME_CONTRIBUTION.APPLICATION_NAME    IS 'FK to APPLICATION when the package has a database component; NULL for runtime-only packages.';
COMMENT ON COLUMN CORE_RUNTIME_CONTRIBUTION.ARTIFACT_URI        IS 'Recorded artifact coordinate or source identity. Never executed by Core.';
COMMENT ON COLUMN CORE_RUNTIME_CONTRIBUTION.ARTIFACT_CHECKSUM   IS 'Immutable content identity checksum.';
COMMENT ON COLUMN CORE_RUNTIME_CONTRIBUTION.CHECKSUM_ALGORITHM  IS 'Algorithm used for ARTIFACT_CHECKSUM.';
COMMENT ON COLUMN CORE_RUNTIME_CONTRIBUTION.PAYLOAD_DIGEST      IS 'Digest of the declared runtime payload contribution.';
COMMENT ON COLUMN CORE_RUNTIME_CONTRIBUTION.MANIFEST_DIGEST     IS 'Digest of the verified package manifest.';
